### ISSUE TITLE
app exits/crashes to home screen when trying to play recording still in progress

### ISSUE THREAD

**Issue by jmechler** [jellyfin-archive/jellyfin-roku-legacy#501]
**Describe the bug**
App crashes when attempting to play a recording in progress

**To Reproduce**
1. Start recording something currently playing or schedule a future recording (must use web or other app for this step)
2. Once the recording has started, open DVR library in roku app
3. navigate to the show, season, and episode
4. press Ok on remote to play
5. get returned to roku home screen

**Expected behavior**
Recording should play (or if this is not support for some reason, a clear error should be returned)

**Logs**
Nothing is logged on server side, at least at default log level.

**Screenshots**

**Additional context**
jellyfin server is docker 10.7.7
jellyfin roku app is version 1.4 build 9
RokuTV 7104X TCL Model 49S04
Software Version 10.5.0 build 4201-30

**Comment by numericOverflow** [comment]
I have the same issue.  Nothing really shown in Jellyfin server logs, the Roku app just crashes.

Is there any way to get debug info from the Roku app to help understand what's happening?

**Comment by numericOverflow** [comment]
BTW, the same thing happens in both the stable & beta versions of Roku app.  I have them both installed, and have several different generations of Roku boxes that all of which exhibit the same behavior, so I don't think it's related to just a single type of Roku device.

More than happy to provide additional detail, just let me know what you need and I can track it down.

**Comment by neilsb** [comment]
I can reproduce this, so will have a look into it.  Would you be able to check if you can play the same in-progress recording on any other clients?  I'm seeing it not loading on the web client which may point at a server issue.

**Comment by neilsb** [comment]
Plainly my memory is not what it used to be.  This is due to a server error - See jellyfin/jellyfin#6550

Although, this error should be caught, and not result in the Roku app crashing - so will get that resolved.

**Comment by jmechler** [comment]
> Plainly my memory is not what it used to be. This is due to a server error - See [jellyfin/jellyfin#6550](https://github.com/jellyfin/jellyfin/issues/6550)
> 
> Although, this error should be caught, and not result in the Roku app crashing - so will get that resolved.

Thanks Neil. Are you thinking resolution of jellyfin#6550 will allow me to play in progress recordings or just prevent the crash?

I believe I could actually play the same recording on my iphone, which may indicate something else? Will need to re-run  tests later today.

**Comment by neilsb** [comment]
> Thanks Neil. Are you thinking resolution of jellyfin#6550 will allow me to play in progress recordings or just prevent the crash?

10.8 (where jellyfin#6550 is fixed) will allow you to play in progress recordings.  I got a version of that running locally and tested it with the current Roku client this morning. 

Would be interesting to hear if you can currently play in-progress recordings on your iPhone.  When I tried it earlier it just sat there and didn't load.  If it does work for you, I'll take another look, but the error message generated on the server when the client requests it, is that the file is already in use, so I'm pretty confident it needs the fix on the server.

**Comment by numericOverflow** [comment]
I was hoping to test this fix too, however when I tried installing the unstable v10.8 (windows) from the downloads, I couldn't get JF server to start. JF kept throwing errors so I figured I must have a mix of old installed 10.7 & portable 10.8 causing the issues.

**Comment by 1hitsong** [comment]
@numericOverflow @neilsb Is this issue now resolved?

**Comment by numericOverflow** [comment]
> @numericOverflow @neilsb Is this issue now resolved?

No, it's not resolved. It's still an issue for me.  Trying to watch a recording in-progress causes the roku app to crash.  

I haven't checked logs or anything of late.  Is there something you want me to look for or test?

FYI - I'm on Win64 Jellyfin v10.8.8

**Comment by numericOverflow** [comment]
> @numericOverflow @neilsb Is this issue now resolved?

I just checked and the issue persists.  

Steps to reproduce:
- Setup a timer to record a TV show via the TV Guide in Jellyfin UI. (I do this via Android JF App)
- Start Jellyfin app on Roku
- Browse to the library that contains TV show recordings.  
- Select the TV show
- Select the Season
- Select the episode that is currently being recorded.
- Roku immediately exits the Jellyfin App and returns to home screen.
- Nothing shows up in Jellyfin server logs (which are set to verbose logging).

I can do more testing if you like, just let me know what would be helpfult to diagnose.

FWIW - I *can* repeat the same steps outlined above on my Android phone and it streams the in-progress recording just fine to the phone, so it seems to be something with the Roku app specifically.

**Comment by jimdogx** [comment]
I just reproduced this.  Taking a look now...
